version: '3'

services:
  sleek-airflow:
    image : sleek-airflow:latest

    volumes:
      - ./airflow:/opt/airflow
      - ./requirements.txt:/requirements.txt
    
    ports:
      - "8080:8080"

    command: airflow standalone